### ISSUE TITLE
CN error

### ISSUE THREAD

**Issue by sdbds** [rulyone/unstable_journey#2]
when i use CN,it happened error

```
2023-04-19 21:32:45,384 - http://localhost:7860 "POST /sdapi/v1/img2img HTTP/1.1" 500 97
2023-04-19 21:32:45,384 - (500, '{"error":"AttributeError","detail":"","body":"","errors":"\'bool\' object has no attribute \'mode\'"}')
Traceback (most recent call last):
  File "H:\unstable_journey\Worker.py", line 23, in run
    result = method(*self.args, **self.kwargs)
  File "H:\unstable_journey\unstable_journey.py", line 1316, in convertCanvasToSDJob
    result1 = self.api.img2img(
  File "H:\unstable_journey\venv\lib\site-packages\webuiapi\webuiapi.py", line 386, in img2img
    return self._to_api_result(response)
  File "H:\unstable_journey\venv\lib\site-packages\webuiapi\webuiapi.py", line 139, in _to_api_result
    raise RuntimeError(response.status_code, response.text)
RuntimeError: (500, '{"error":"AttributeError","detail":"","body":"","errors":"\'bool\' object has no attribute \'mode\'"}')
2023-04-19 21:32:45,385 - Error trying to execute worker for method <bound method MainWindow.convertCanvasToSDJob of <__main__.MainWindow(0x1edfe3e65c0, name="MainWindow") at 0x000001EDFF3E9480>>. See above logs to debug issue.
```

**Comment by rulyone** [comment]
That's a 500 error from the automatic1111 webui. I'm guessing this is an issue with that project given that I'm unable to reproduce the error.

I'm using CN right now withtout issues, except sometimes it gives me a `Max retries exceeded with url` once in a while. Also an issue from the backend.

**Comment by sdbds** [comment]
> That's a 500 error from the automatic1111 webui. I'm guessing this is an issue with that project given that I'm unable to reproduce the error.
> 
> I'm using CN right now withtout issues, except sometimes it gives me a `Max retries exceeded with url` once in a while. Also an issue from the backend.

i update CN and no erro now,thank u for answering
